// Date: 10/09/2018 20:10:28
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package mod.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTranslater extends ModelBase {
	ModelRenderer box1;
	ModelRenderer box2;
	ModelRenderer box3;
	ModelRenderer box4;
	ModelRenderer box5;
	ModelRenderer box6;

	public ModelTranslater() {
		textureWidth = 64;
		textureHeight = 32;

		box1 = new ModelRenderer(this, 8, 8);
		box1.addBox(-1F, -1F, -1F, 2, 2, 2);
		box1.setRotationPoint(0F, -1F, 0F);
		box1.setTextureSize(64, 32);
		box1.mirror = true;
		setRotation(box1, 0F, 0F, 0F);
		box2 = new ModelRenderer(this, 0, 17);
		box2.addBox(-1F, 0F, -4F, 2, 1, 2);
		box2.setRotationPoint(0F, 0F, 0F);
		box2.setTextureSize(64, 32);
		box2.mirror = true;
		setRotation(box2, 0F, 0F, 0F);
		box3 = new ModelRenderer(this, 0, 8);
		box3.addBox(-4F, 0F, -1F, 2, 1, 2);
		box3.setRotationPoint(0F, 0F, 0F);
		box3.setTextureSize(64, 32);
		box3.mirror = true;
		setRotation(box3, 0F, 0F, 0F);
		box4 = new ModelRenderer(this, 0, 14);
		box4.addBox(2F, 0F, -1F, 2, 1, 2);
		box4.setRotationPoint(0F, 0F, 0F);
		box4.setTextureSize(64, 32);
		box4.mirror = true;
		setRotation(box4, 0F, 0F, 0F);
		box5 = new ModelRenderer(this, 0, 11);
		box5.addBox(-1F, 0F, 2F, 2, 1, 2);
		box5.setRotationPoint(0F, 0F, 0F);
		box5.setTextureSize(64, 32);
		box5.mirror = true;
		setRotation(box5, 0F, 0F, 0F);
		box6 = new ModelRenderer(this, 0, 0);
		box6.addBox(-3F, 0F, -3F, 6, 2, 6);
		box6.setRotationPoint(0F, -1F, 0F);
		box6.setTextureSize(64, 32);
		box6.mirror = true;
		setRotation(box6, 0F, 0F, 0F);
	}

	public void renderAll() 
	{
		float f5 = 0.0625F;
		box1.render(f5);
		box2.render(f5);
		box3.render(f5);
		box4.render(f5);
		box5.render(f5);
		box6.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
